
source: .
paths:
  uploads: media
  static: .
  pages: .

collections_config:
  pages:
    path: .
    output: true
    filter:
      base: none
      glob: "**/*.html"

_enabled_editors:
  - visual
  - source
